# Generated by Django 3.1.1 on 2020-09-21 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dapi', '0004_auto_20200921_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tz',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='end_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
