# Generated by Django 3.1.1 on 2020-09-22 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dapi', '0005_auto_20200921_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='start_time',
        ),
    ]
