# Generated by Django 3.1.1 on 2020-09-22 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dapi', '0006_auto_20200922_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='start_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
