# Generated by Django 3.1.1 on 2020-09-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dapi', '0012_auto_20200922_0506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='start_time',
        ),
    ]
