# Generated by Django 3.1.1 on 2020-09-22 13:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dapi', '0013_remove_user_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 22, 13, 7, 57, 515707, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='end_time',
            field=models.TimeField(),
        ),
    ]
