# Generated by Django 3.1.1 on 2020-09-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapi', '0014_auto_20200922_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='end_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
