# Generated by Django 3.1.1 on 2020-09-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapi', '0015_auto_20200922_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
