# Generated by Django 3.1.1 on 2020-09-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dapi', '0017_remove_user_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='end_time',
        ),
    ]
